name: clay_terratorch
channels:
  - conda-forge
dependencies:
  - python=3.11
  - gdal
  - rasterio
  - rioxarray
  - pyproj
  - numpy
  - pandas
  - pyyaml
  - tqdm
  - scikit-learn
  - pip
  - pip:
      - terratorch>=0.99
      - odc-stac>=0.3
      - pystac-client>=0.7
      - planetary-computer>=1.0
